In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## FEA-PART

In [2]:
df=pd.read_csv('titanic_data.csv')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    object 
 3   age          713 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   embarked     887 non-null    object 
 8   class        889 non-null    object 
 9   who          889 non-null    object 
 10  adult_male   889 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  887 non-null    object 
 13  alive        889 non-null    object 
 14  alone        889 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.2+ KB


In [4]:
df.shape

(889, 15)

In [5]:
df.dropna().shape

(182, 15)

In [6]:
df.dropna(axis=1)

survived  pclass     sex  sibsp  parch     fare   class    who  \
0           0       3    male      1      0   7.2500   Third    man   
1           1       1  female      1      0  71.2833   First  woman   
2           1       3  female      0      0   7.9250   Third  woman   
3           1       1  female      1      0  53.1000   First  woman   
4           0       3    male      0      0   8.0500   Third    man   
..        ...     ...     ...    ...    ...      ...     ...    ...   
884         0       2    male      0      0  13.0000  Second    man   
885         1       1  female      0      0  30.0000   First  woman   
886         0       3  female      1      2  23.4500   Third  woman   
887         1       1    male      0      0  30.0000   First    man   
888         0       3    male      0      0   7.7500   Third    man   

     adult_male alive  alone  
0          True    no  False  
1         False   yes  False  
2         False   yes   True  
3         False   yes  False  
4          True    no   True  
..          ...   ...    ...  
884        True    no   True  
885       False   yes   True  
886       False    no  False  
887        True   yes   True  
888        True    no   True  

[889 rows x 11 columns]

In [7]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
884         0       2    male  27.0      0      0  13.0000        S  Second   
885         1       1  female  19.0      0      0  30.0000        S   First   
886         0       3  female   NaN      1      2  23.4500        S   Third   
887         1       1    male  26.0      0      0  30.0000        C   First   
888         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
884    man        True  NaN  Southampton    no   True  
885  woman       False    B  Southampton   yes   True  
886  woman       False  NaN  Southampton    no  False  
887    man        True    C    Cherbourg   yes   True  
888    man        True  NaN   Queenstown    no   True  

[889 rows x 15 columns]

In [8]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
df['age']=df['age'].fillna(df['age'].median())

In [10]:
df['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
884    27.0
885    19.0
886    28.0
887    26.0
888    32.0
Name: age, Length: 889, dtype: float64

In [11]:
df['age'].isnull().sum()

np.int64(0)

In [12]:
df['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [13]:
df['embark_town'].mode()

0    Southampton
Name: embark_town, dtype: object

In [14]:
df['embark_town']=df['embark_town'].fillna(df['embark_town'].mode()[0])


In [15]:
df['embark_town']

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...     
884    Southampton
885    Southampton
886    Southampton
887      Cherbourg
888     Queenstown
Name: embark_town, Length: 889, dtype: object

In [16]:
df['embark_town'].isnull().sum()

np.int64(0)

In [17]:
df.drop(['embarked','class','deck','alive'],axis=1,inplace=True)

In [18]:
df .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    object 
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   who          889 non-null    object 
 8   adult_male   889 non-null    bool   
 9   embark_town  889 non-null    object 
 10  alone        889 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 64.4+ KB


In [19]:
df['sex']=df['sex'].map({'male':1, 'female':2,})

In [20]:
df['sex'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 889 entries, 0 to 888
Series name: sex
Non-Null Count  Dtype
--------------  -----
889 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB


In [21]:
df['sex'].isnull().sum()

np.int64(0)

In [22]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [23]:
df['who']=df['who'].map({'man':1, 'woman':2,'child':3})

In [24]:
df['who'].isnull().sum()

np.int64(0)

In [25]:
df['adult_male'].unique()

array([ True, False])

In [26]:
df['adult_male'] = df['adult_male'].astype(str).str.upper().map({'TRUE': 1, 'FALSE': 0})



In [27]:
df['adult_male'] = df['adult_male'].astype(int)


In [28]:
df['adult_male'].isnull().sum()

np.int64(0)

In [29]:
df['adult_male'].unique()

array([1, 0])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    int64  
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   who          889 non-null    int64  
 8   adult_male   889 non-null    int64  
 9   embark_town  889 non-null    object 
 10  alone        889 non-null    bool   
dtypes: bool(1), float64(2), int64(7), object(1)
memory usage: 70.4+ KB


In [31]:
df['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown'], dtype=object)

In [32]:
df['embark_town']=df['embark_town'].map({'Southampton':1, 'Cherbourg':2,'Queenstown':3})

In [33]:
df['embark_town'].isnull().sum()

np.int64(0)

In [34]:
df['alone'].unique()

array([False,  True])

In [35]:
df['alone'] = df['alone'].astype(str).str.upper().map({'TRUE': 1, 'FALSE': 0})



In [36]:
df['adult_male'] = df['adult_male'].astype(int)


In [37]:
df['alone'].unique()

array([0, 1])

In [38]:
df['alone'].isnull().sum()

np.int64(0)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    int64  
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   who          889 non-null    int64  
 8   adult_male   889 non-null    int64  
 9   embark_town  889 non-null    int64  
 10  alone        889 non-null    int64  
dtypes: float64(2), int64(9)
memory usage: 76.5 KB


In [40]:
df.to_csv('titanic_cleaned_csv')

## Model Training

In [41]:
df=pd.read_csv('titanic_cleaned_csv')

In [42]:
df

Unnamed: 0  survived  pclass  sex   age  sibsp  parch     fare  who  \
0             0         0       3    1  22.0      1      0   7.2500    1   
1             1         1       1    2  38.0      1      0  71.2833    2   
2             2         1       3    2  26.0      0      0   7.9250    2   
3             3         1       1    2  35.0      1      0  53.1000    2   
4             4         0       3    1  35.0      0      0   8.0500    1   
..          ...       ...     ...  ...   ...    ...    ...      ...  ...   
884         884         0       2    1  27.0      0      0  13.0000    1   
885         885         1       1    2  19.0      0      0  30.0000    2   
886         886         0       3    2  28.0      1      2  23.4500    2   
887         887         1       1    1  26.0      0      0  30.0000    1   
888         888         0       3    1  32.0      0      0   7.7500    1   

     adult_male  embark_town  alone  
0             1            1      0  
1             0            2      0  
2             0            1      1  
3             0            1      0  
4             1            1      1  
..          ...          ...    ...  
884           1            1      1  
885           0            1      1  
886           0            1      0  
887           1            2      1  
888           1            3      1  

[889 rows x 12 columns]

In [43]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    int64  
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   who          889 non-null    int64  
 8   adult_male   889 non-null    int64  
 9   embark_town  889 non-null    int64  
 10  alone        889 non-null    int64  
dtypes: float64(2), int64(9)
memory usage: 76.5 KB


In [45]:
X = df.drop(df[["survived"]], axis=1)
y = df[["survived"]]

In [46]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pclass       889 non-null    int64  
 1   sex          889 non-null    int64  
 2   age          889 non-null    float64
 3   sibsp        889 non-null    int64  
 4   parch        889 non-null    int64  
 5   fare         889 non-null    float64
 6   who          889 non-null    int64  
 7   adult_male   889 non-null    int64  
 8   embark_town  889 non-null    int64  
 9   alone        889 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 69.6 KB


In [47]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB


In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [49]:
X_train.shape,X_test.shape

((666, 10), (223, 10))

In [50]:
y_train


survived
375         1
457         1
731         0
506         1
828         1
..        ...
106         1
270         1
860         1
435         0
102         0

[666 rows x 1 columns]

In [51]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

## Logistic Regression

In [52]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)
print(y_pred)

[0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1
 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 0 1 0
 0 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 0 1
 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1
 1]


d:\DATA SCIENCE\PYTHON\DEPLOYMENTS ALGORITHIMS (ALL  DATA SETS)\Titanic data set\mlenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
d:\DATA SCIENCE\PYTHON\DEPLOYMENTS ALGORITHIMS (ALL  DATA SETS)\Titanic data set\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [53]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [54]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.8251121076233184
              precision    recall  f1-score   support

           0       0.86      0.85      0.86       137
           1       0.77      0.78      0.77        86

    accuracy                           0.83       223
   macro avg       0.82      0.82      0.82       223
weighted avg       0.83      0.83      0.83       223

[[117  20]
 [ 19  67]]


# svc

In [55]:
from sklearn.svm import SVC

In [59]:
SVC.coef_

In [60]:
from sklearn.metrics import classification_report,confusion_matrix

In [61]:
svc=SVC(kernel='linear')
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

d:\DATA SCIENCE\PYTHON\DEPLOYMENTS ALGORITHIMS (ALL  DATA SETS)\Titanic data set\mlenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8251121076233184
              precision    recall  f1-score   support

           0       0.85      0.86      0.85       136
           1       0.78      0.76      0.77        87

    accuracy                           0.82       223
   macro avg       0.81      0.81      0.81       223
weighted avg       0.82      0.82      0.82       223

[[117  19]
 [ 21  66]]


In [62]:
rbf=SVC(kernel='rbf')
rbf.fit(X_train,y_train)
y_pred=rbf.predict(X_test)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8251121076233184
              precision    recall  f1-score   support

           0       0.65      0.90      0.76       136
           1       0.63      0.25      0.36        87

    accuracy                           0.65       223
   macro avg       0.64      0.58      0.56       223
weighted avg       0.64      0.65      0.60       223

[[123  13]
 [ 65  22]]


d:\DATA SCIENCE\PYTHON\DEPLOYMENTS ALGORITHIMS (ALL  DATA SETS)\Titanic data set\mlenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
poly=SVC(kernel='poly')
poly.fit(X_train,y_train)
y_pred=poly.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.94      0.75       136
           1       0.56      0.11      0.19        87

    accuracy                           0.62       223
   macro avg       0.59      0.53      0.47       223
weighted avg       0.60      0.62      0.53       223

[[128   8]
 [ 77  10]]


d:\DATA SCIENCE\PYTHON\DEPLOYMENTS ALGORITHIMS (ALL  DATA SETS)\Titanic data set\mlenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# exporting to pickle file

In [64]:
import pickle
from flask import Flask,request,jsonify,render_template
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

application = Flask(__name__)
app=application

In [65]:
import pickle
pickle.dump(logistic,open('logistic.pkl','wb'))
pickle.dump(scaler,open('scaler.pkl','wb'))

In [66]:
model_logistic=pickle.load(open('logistic.pkl','rb'))
model_scaler=pickle.load(open('scaler.pkl','rb'))

In [67]:
model_logistic.predict(X_test)

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1])